FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY eureka-server.jar /app/eureka-server.jar
# Expone el puerto que utiliza el Config Server
EXPOSE 8761

ENTRYPOINT ["java", "-jar", "/app/eureka-server.jar"]
