spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: hotel
          uri: lb://hotel
          predicates:
            - Path=/shotel/**
          filters:
            - RewritePath=/shotel/*, /
        - id: vuelos
          uri: lb://vuelo
          predicates:
            - Path=/svuelo/**
          filters:
            - RewritePath=/svuelo/*, /
        - id: reservas
          uri: lb://reservas
          predicates:
            - Path=/sreserva/**
          filters:
            - RewritePath=/sreserva/*, /
server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/