FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY config-server.jar /app/config-server.jar
# Expone el puerto que utiliza el Config Server
EXPOSE 7777

ENTRYPOINT ["java", "-jar", "/app/config-server.jar"]
